language: node_js
node_js:
  - '4.2'
  
env:
  global:
  - secure: i00ydLc3+h4oeriibbKQMOOnxDEtlYqSBE1tzg2jfK2TkFQI25ZQZhBCxvfQg1dnXuM02Q8peNiDp4JxA4MLS2oJtr1fPD5nQrSfMfWCzfUdoXDdWclF+pkDZdZA3hORaapl9IS9rUIpWjbO2ug51YZ5uRTT3ZVmAOUV8uElatyoiuuJSuT4nHYtea83XgLgXekCyXUcOipZmUuHfuOy+E00WMUraj/cpawUl7/8nHovW4NchKgMEQci0asvzaaer4zQXOTfivWVpnwASr8CVArbf/jhZ+WpaAzDh924/cG52VkYRF2+ikmRklW7eP1lxFQfHgMlq+YPKFIG62T1Is5lCqlngf5vO2Ct0kyD3tLp5hMPxgpJARiPuL3kUsLP39ac8BiaMQJydpo7OquTduGqaiehpers3hxMgXTJZApZLWH1C6zBMhe5qihK3It72/tUTHLWTHyeC4PyzHkeT0qjhg1nL+d0odlie+dXaHD93hdCen3qgekHV6n+rWZVhIYtM7njkmGeCYLZTV+WrilXawUcEzLulJgMDrXUUb7RWP4dCNql7PWiAMSn4Cdd+B7yqFz8WMoSn/u2Ys3ynaPoyMQ1bLiBczF2Nx1GEODum/zPKqjtTaAJUy8B11Jge94qRTMwe7EQt1P2tZRLBzdpn/Vl/FWHtoxsG9ASfuY=
  - secure: RXGRXYQ5YBSbNqebXLT3Az4XBZkg84WvYVt15KwziU5Mx/Dfcm6ym9B3s7JY9YgGdYSOFpcYBToX46jTXZluxsOQNk0TV/5GodY2K+aUj9TEpLkOPMHMz39FS16pLTo1hfgWuSVyKOEyPI58DioFqGDAcmg1CUsjbpV8uzXYo2HzUmr/SGo9TVtt+drr3XfP6WiOhzeuHJhfviwDvzmYyvjOAMJPt/Lz+HC3PuTbjk4e+iXJPEMu8JcBhS0jIooYMTHX57tz7gUeKMO5JEbKjyhH9qpNDTArnESfQdMTHRZpKjiA1Vle1L4Mzm9sarwSnpwxYphWMXkSlNcjLSoRUvYZTSzkH7U1k0jwCZQUAN+eSS4nFtLWPdw4LLAB/oMIHE1Ct8L0vtDXbUFONrJqRut9Tr4Wb5LheBM6YR8G7E/a477yWDHdaHElP5dofEMT+j0fo7kQ34CcfdHeObArMNp4Bcz8oK4WqOpc77DreIAJSNaYE9UkfmYOw27K/8ejYEuxHbOfSRKjPi3XZnuhRdklM8X3hjfqwrWjLyduRhSbev1MFsWlOtv17aR8ntNJl/aUGWYOE54hHviNq3ZrdYlxepYW682drT2/kBNu6rRua+2Rhf0qGQLCvCs6jy/FMPuyCRJuvvcwTaW6ND3K5RdLOht888+vYWyjcyN3FZw=
  - secure: Qu6a8j7mXCWlv5uqud6QT0yyPlvsBKz8bvHLg3ZVcTsT6tCgTVjvaypl9tumirr6Nf7r50TiighfP2Gs9HZJh4zRaeprWcZcFZpdwTKw6dSAyOJ7zKcxB60ZQ9MLfQuyrS2U5JYPC51oAr0FhJ6/Fb9dH3rC9nWb16dJXffC3cCxDL52wl2iOhmpZQbKL5MwFbCfhlbcy7ACxVrpUg4xJ1sZcom+DB8I6z1WN6kwEmC833k9u+VLYuB2aLcTWGpAQBex0fjfs9iqHMmFbh4Lg+dPF8wJl+ygwsNCJdLUEv0JTKBg2Z6iQNW2/qVkWUXEawpOYw0kTUQOGFq5t+Cd/oL8c0KyFgPb8wGNW6G35EYTGOxFS9OHaYthWREEXXwtirVJuVx/qOPuuuT6k1lYtOVu7+WLp9LOprl9jniZTtDyfeQ8DwpY0sX1BQokQJqUTe4cLTYCk1yU3fHvmm/uMzjDdBE5CkZmEakXc0ynHpxu2JYLbGTvgw51VUPP87h4VZahkY5cfAyyRWahbIGly7oBI6G8Cm9qkQM41fwhG0r6gIf0XjdEZzrJ5Bhk1R9xiFq+Op1tf+YjEan7dgVbuz6GWxhQ3UwomFPQrlns6saTB/x2hLsmpUq6pXWcQtsz/RMeGlZVBJ93o5Il4SItE0zULYfNfo07CbPIy0EOZAs=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
